Moved to form freeglut to glut
git-svn-id: file:///home/user/src/subversion/wampirzce/trunk@13 e1c457e2-c742-46e7-b5f9-8b95fcc9e92b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3763,18 +3763,18 @@ echo "$as_me: error: No sys/time.h found!" >&2;}
 fi
 
 
-if test "${ac_cv_header_GL_freeglut_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for GL/freeglut.h" >&5
-echo $ECHO_N "checking for GL/freeglut.h... $ECHO_C" >&6
-if test "${ac_cv_header_GL_freeglut_h+set}" = set; then
+if test "${ac_cv_header_GL_glut_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for GL/glut.h" >&5
+echo $ECHO_N "checking for GL/glut.h... $ECHO_C" >&6
+if test "${ac_cv_header_GL_glut_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_GL_freeglut_h" >&5
-echo "${ECHO_T}$ac_cv_header_GL_freeglut_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_GL_glut_h" >&5
+echo "${ECHO_T}$ac_cv_header_GL_glut_h" >&6
 else
   # Is the header compilable?
-echo "$as_me:$LINENO: checking GL/freeglut.h usability" >&5
-echo $ECHO_N "checking GL/freeglut.h usability... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking GL/glut.h usability" >&5
+echo $ECHO_N "checking GL/glut.h usability... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -3783,7 +3783,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <GL/freeglut.h>
+#include <GL/glut.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -3809,8 +3809,8 @@ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
 echo "${ECHO_T}$ac_header_compiler" >&6
 
 # Is the header present?
-echo "$as_me:$LINENO: checking GL/freeglut.h presence" >&5
-echo $ECHO_N "checking GL/freeglut.h presence... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking GL/glut.h presence" >&5
+echo $ECHO_N "checking GL/glut.h presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -3818,7 +3818,7 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <GL/freeglut.h>
+#include <GL/glut.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -3851,10 +3851,10 @@ echo "${ECHO_T}$ac_header_preproc" >&6
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc in
   yes:no )
-    { echo "$as_me:$LINENO: WARNING: GL/freeglut.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: GL/freeglut.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: GL/freeglut.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: GL/freeglut.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: GL/glut.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: GL/glut.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: GL/glut.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: GL/glut.h: proceeding with the preprocessor's result" >&2;}
     (
       cat <<\_ASBOX
 ## ------------------------------------ ##
@@ -3865,12 +3865,12 @@ _ASBOX
       sed "s/^/$as_me: WARNING:     /" >&2
     ;;
   no:yes )
-    { echo "$as_me:$LINENO: WARNING: GL/freeglut.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: GL/freeglut.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: GL/freeglut.h: check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: GL/freeglut.h: check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: GL/freeglut.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: GL/freeglut.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: GL/glut.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: GL/glut.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: GL/glut.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: GL/glut.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: GL/glut.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: GL/glut.h: proceeding with the preprocessor's result" >&2;}
     (
       cat <<\_ASBOX
 ## ------------------------------------ ##
@@ -3881,22 +3881,22 @@ _ASBOX
       sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-echo "$as_me:$LINENO: checking for GL/freeglut.h" >&5
-echo $ECHO_N "checking for GL/freeglut.h... $ECHO_C" >&6
-if test "${ac_cv_header_GL_freeglut_h+set}" = set; then
+echo "$as_me:$LINENO: checking for GL/glut.h" >&5
+echo $ECHO_N "checking for GL/glut.h... $ECHO_C" >&6
+if test "${ac_cv_header_GL_glut_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_GL_freeglut_h=$ac_header_preproc
+  ac_cv_header_GL_glut_h=$ac_header_preproc
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_GL_freeglut_h" >&5
-echo "${ECHO_T}$ac_cv_header_GL_freeglut_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_GL_glut_h" >&5
+echo "${ECHO_T}$ac_cv_header_GL_glut_h" >&6
 
 fi
-if test $ac_cv_header_GL_freeglut_h = yes; then
+if test $ac_cv_header_GL_glut_h = yes; then
   :
 else
-  { { echo "$as_me:$LINENO: error: No GL/freeglut.h found!" >&5
-echo "$as_me: error: No GL/freeglut.h found!" >&2;}
+  { { echo "$as_me:$LINENO: error: No GL/glut.h found!" >&5
+echo "$as_me: error: No GL/glut.h found!" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -3905,10 +3905,6 @@ fi
 # Checks for library functions.
 #AC_CHECK_LIB(Xxf86vm,XF86VidModeSetViewPort,,AC_MSG_ERROR(Xxf86vm))
 #AC_CHECK_LIB(freeglut-1.3,glutInit,,AC_MSG_ERROR(freeglut-1.3))
-
-#-DGL_FULL_SCREEN
-CXXFLAGS="-Wall -ffast-math -funroll-loops -O3 -mcpu=athlon -march=athlon"
-LDFLAGS="-L/usr/X11R6/lib -lfreeglut-1.3 -lXxf86vm"
 
                     ac_config_files="$ac_config_files Makefile src/Makefile"
 
