Moved to SDL :-)
git-svn-id: file:///home/user/src/subversion/wampirzce/trunk@19 e1c457e2-c742-46e7-b5f9-8b95fcc9e92b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3901,6 +3901,282 @@ echo "$as_me: error: GL/glut.h not found!" >&2;}
 fi
 
 
+if test "${ac_cv_header_SDL_SDL_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for SDL/SDL.h" >&5
+echo $ECHO_N "checking for SDL/SDL.h... $ECHO_C" >&6
+if test "${ac_cv_header_SDL_SDL_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_SDL_SDL_h" >&5
+echo "${ECHO_T}$ac_cv_header_SDL_SDL_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking SDL/SDL.h usability" >&5
+echo $ECHO_N "checking SDL/SDL.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <SDL/SDL.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking SDL/SDL.h presence" >&5
+echo $ECHO_N "checking SDL/SDL.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <SDL/SDL.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: SDL/SDL.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: SDL/SDL.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: SDL/SDL.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: SDL/SDL.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: SDL/SDL.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for SDL/SDL.h" >&5
+echo $ECHO_N "checking for SDL/SDL.h... $ECHO_C" >&6
+if test "${ac_cv_header_SDL_SDL_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_SDL_SDL_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_SDL_SDL_h" >&5
+echo "${ECHO_T}$ac_cv_header_SDL_SDL_h" >&6
+
+fi
+if test $ac_cv_header_SDL_SDL_h = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: SDL/SDL.h not found!" >&5
+echo "$as_me: error: SDL/SDL.h not found!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+if test "${ac_cv_header_SDL_SDL_opengl_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for SDL/SDL_opengl.h" >&5
+echo $ECHO_N "checking for SDL/SDL_opengl.h... $ECHO_C" >&6
+if test "${ac_cv_header_SDL_SDL_opengl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_SDL_SDL_opengl_h" >&5
+echo "${ECHO_T}$ac_cv_header_SDL_SDL_opengl_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking SDL/SDL_opengl.h usability" >&5
+echo $ECHO_N "checking SDL/SDL_opengl.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <SDL/SDL_opengl.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking SDL/SDL_opengl.h presence" >&5
+echo $ECHO_N "checking SDL/SDL_opengl.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <SDL/SDL_opengl.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL_opengl.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: SDL/SDL_opengl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL_opengl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: SDL/SDL_opengl.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL_opengl.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: SDL/SDL_opengl.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL_opengl.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: SDL/SDL_opengl.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL/SDL_opengl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: SDL/SDL_opengl.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for SDL/SDL_opengl.h" >&5
+echo $ECHO_N "checking for SDL/SDL_opengl.h... $ECHO_C" >&6
+if test "${ac_cv_header_SDL_SDL_opengl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_SDL_SDL_opengl_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_SDL_SDL_opengl_h" >&5
+echo "${ECHO_T}$ac_cv_header_SDL_SDL_opengl_h" >&6
+
+fi
+if test $ac_cv_header_SDL_SDL_opengl_h = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: SDL/SDL_opengl.h not found!" >&5
+echo "$as_me: error: SDL/SDL_opengl.h not found!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 
 # Checks for library functions.
 echo "$as_me:$LINENO: checking for main in -lGL" >&5
@@ -3959,7 +4235,21 @@ echo "$as_me: error: libGL not found!" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-LIBS="$LIBS -lglut"
+LIBS="$LIBS -L/usr/X11R6/lib -lglut"
+
+# Check for SDL (via sdl-config)
+echo "$as_me:$LINENO: checking for SDL" >&5
+echo $ECHO_N "checking for SDL... $ECHO_C" >&6
+if test -x "`which sdl-config 2>/dev/null`"; then
+    FLAGS="$FLAGS `sdl-config --cflags`"
+    LIBS="$LIBS `sdl-config --libs`"
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+    { { echo "$as_me:$LINENO: error: SDL not found!" >&5
+echo "$as_me: error: SDL not found!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
                     ac_config_files="$ac_config_files Makefile src/Makefile"
 
